print("****WELCOME ****")
name=input("enter your name:")
age=int(input("enter your age :"))
college=input("enter your college name:")
course=input("enter your course specialised with")
print("----student profile---")
print("NAME:",name)
print("AGE:",age)
print("COLLEGE:",college)
print("COURSE:",course)
print("****Thankyou for your kind information*****")